- hosts: web
  gather_facts: false
  connection: aws_ssm
  
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy web content
      copy:
        src: index.html
        dest: /usr/share/nginx/html
        mode: '0644'

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: true
